/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sistemalocacao;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;



/**
 *
 * @author leticia
 */
public class EquipamentoUI extends javax.swing.JPanel {
    
    private boolean isUpdating = false; // Evita loops durante o update

    public JPanel getPanel() {
        return panelEquip;
    }
    
    private void adicionarListenerTxtValorDiaria() {
    txtValorDiaria.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            formatInput();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            formatInput();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            formatInput();
        }
    });
}

private void formatInput() {
    if (isUpdating) return;

    isUpdating = true;
    String input = txtValorDiaria.getText();

    // Remove caracteres indesejados (mantém apenas números e vírgula)
    input = input.replace(".", "").replace(",", "");

    if (!input.isEmpty()) {
        try {
            // Converte para número e ajusta para exibição formatada
            double value = Double.parseDouble(input) / 100; // Ajusta para casas decimais
            txtValorDiaria.setText(Utils.formatarMonetario(value)); // Usa Utils aqui
        } catch (NumberFormatException ex) {
            txtValorDiaria.setText(""); // Limpa se houver erro inesperado na formatação
        }
    }

    isUpdating = false; // Libera para próximas atualizações
}
    public EquipamentoUI() {
        initComponents();
        adicionarListenerTxtValorDiaria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEquip = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescricaoEquip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorDiaria = new javax.swing.JTextField();
        btnCadEquip = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNomeEquip = new javax.swing.JTextField();

        setOpaque(false);

        panelEquip.setPreferredSize(new java.awt.Dimension(616, 616));

        jLabel1.setText("Nome do Equipamento:");

        jLabel2.setText("Descrição (opcional):");

        txtDescricaoEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoEquipActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor da Locação diária: R$");

        txtValorDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDiariaActionPerformed(evt);
            }
        });

        btnCadEquip.setText("Cadastrar Equipamento");
        btnCadEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEquipActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNomeEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEquipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEquipLayout = new javax.swing.GroupLayout(panelEquip);
        panelEquip.setLayout(panelEquipLayout);
        panelEquipLayout.setHorizontalGroup(
            panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipLayout.createSequentialGroup()
                .addGroup(panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEquipLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(txtDescricaoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEquipLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEquipLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeEquip))
                            .addComponent(jLabel2)))
                    .addGroup(panelEquipLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEquipLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelEquipLayout.setVerticalGroup(
            panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricaoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(panelEquipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEquipActionPerformed
        String nomeEquip = txtNomeEquip.getText();
    String descricaoEquip = txtDescricaoEquip.getText();

    try {
        // Remove pontos e substitui vírgula por ponto para conversão numérica
        String valorDigitado = txtValorDiaria.getText().replace(".", "").replace(",", ".");
        double valorDiaria = Double.parseDouble(valorDigitado);

        // Lógica de cadastro e exibição
        Equipamento equipamento = new Equipamento(nomeEquip, descricaoEquip, valorDiaria);
        GerenciadorDados.adicionarEquipamento(equipamento);

        // Formata o valor com Utils
        String valorFormatado = Utils.formatarMonetario(valorDiaria);

        JOptionPane.showMessageDialog(panelEquip, "Equipamento registrado com sucesso: \n" +
                "Nome: " + nomeEquip + "\n" +
                "Descrição: " + descricaoEquip + "\n" +
                "Valor de Locação Diária: " + valorFormatado);

        // Limpa os campos
        txtNomeEquip.setText("");
        txtDescricaoEquip.setText("");
        txtValorDiaria.setText("");
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(panelEquip, "Por favor, insira um valor válido no campo de locação diária.",
                "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnCadEquipActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(panelEquip, "Cadastro de Equipamento Cancelado", "Cancelado", JOptionPane.INFORMATION_MESSAGE);

                txtNomeEquip.setText("");
                txtDescricaoEquip.setText("");
                txtValorDiaria.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtValorDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDiariaActionPerformed

    }//GEN-LAST:event_txtValorDiariaActionPerformed

    private void txtDescricaoEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoEquipActionPerformed

    private void txtNomeEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEquipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadEquip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelEquip;
    private javax.swing.JTextField txtDescricaoEquip;
    private javax.swing.JTextField txtNomeEquip;
    private javax.swing.JTextField txtValorDiaria;
    // End of variables declaration//GEN-END:variables
}
